FROM node:20-alpine AS base
ENV NEXT_TELEMETRY_DISABLED=1
WORKDIR /app

FROM base AS deps
RUN apk add --no-cache libc6-compat
COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci

FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ARG BILLING_PREMIUM_PRICE_MONTHLY
ARG BILLING_PREMIUM_PRICE_YEARLY
ARG BILLING_ULTIMATE_PRICE_MONTHLY
ARG BILLING_ULTIMATE_PRICE_YEARLY
ARG PLAN_FREE_MAX_DECKS
ARG PLAN_FREE_MAX_QUESTIONS_PER_DECK
ARG PLAN_FREE_DAILY_EXPLANATION_SECONDS
ARG PLAN_PREMIUM_MAX_DECKS
ARG PLAN_PREMIUM_MAX_QUESTIONS_PER_DECK
ARG PLAN_PREMIUM_DAILY_EXPLANATION_MINUTES
ARG PLAN_ULTIMATE_MAX_DECKS
ARG PLAN_ULTIMATE_MAX_QUESTIONS_PER_DECK
ARG PLAN_ULTIMATE_DAILY_EXPLANATION_MINUTES
ENV BILLING_PREMIUM_PRICE_MONTHLY=$BILLING_PREMIUM_PRICE_MONTHLY
ENV BILLING_PREMIUM_PRICE_YEARLY=$BILLING_PREMIUM_PRICE_YEARLY
ENV BILLING_ULTIMATE_PRICE_MONTHLY=$BILLING_ULTIMATE_PRICE_MONTHLY
ENV BILLING_ULTIMATE_PRICE_YEARLY=$BILLING_ULTIMATE_PRICE_YEARLY
ENV PLAN_FREE_MAX_DECKS=$PLAN_FREE_MAX_DECKS
ENV PLAN_FREE_MAX_QUESTIONS_PER_DECK=$PLAN_FREE_MAX_QUESTIONS_PER_DECK
ENV PLAN_FREE_DAILY_EXPLANATION_SECONDS=$PLAN_FREE_DAILY_EXPLANATION_SECONDS
ENV PLAN_PREMIUM_MAX_DECKS=$PLAN_PREMIUM_MAX_DECKS
ENV PLAN_PREMIUM_MAX_QUESTIONS_PER_DECK=$PLAN_PREMIUM_MAX_QUESTIONS_PER_DECK
ENV PLAN_PREMIUM_DAILY_EXPLANATION_MINUTES=$PLAN_PREMIUM_DAILY_EXPLANATION_MINUTES
ENV PLAN_ULTIMATE_MAX_DECKS=$PLAN_ULTIMATE_MAX_DECKS
ENV PLAN_ULTIMATE_MAX_QUESTIONS_PER_DECK=$PLAN_ULTIMATE_MAX_QUESTIONS_PER_DECK
ENV PLAN_ULTIMATE_DAILY_EXPLANATION_MINUTES=$PLAN_ULTIMATE_DAILY_EXPLANATION_MINUTES
RUN npx prisma generate
RUN npm run build

FROM node:20-alpine AS runner
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 --ingroup nodejs nextjs

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/@prisma ./node_modules/@prisma

USER nextjs

EXPOSE 8083

ENV PORT=8083
ENV HOSTNAME=0.0.0.0

CMD ["node", "server.js"]
